package com.tinytongtong.androidstudy.gson;

/**
 * @Description: gson解析
 * @Author wangjianzhou
 * @Date 2022/3/13 5:29 PM
 */
public class GsonSource {
    /**
     * 单个对象
     */
    public static final String SIMPLE_REPO = "{\n" +
            "    \"id\": 82627728,\n" +
            "    \"node_id\": \"MDEwOlJlcG9zaXRvcnk4MjYyNzcyOA==\",\n" +
            "    \"name\": \"Android\",\n" +
            "    \"full_name\": \"tinyvampirepudge/Android\",\n" +
            "    \"private\": false,\n" +
            "    \"owner\": {\n" +
            "        \"login\": \"tinyvampirepudge\",\n" +
            "        \"id\": 15034726,\n" +
            "        \"node_id\": \"MDQ6VXNlcjE1MDM0NzI2\",\n" +
            "        \"avatar_url\": \"https://avatars.githubusercontent.com/u/15034726?v=4\",\n" +
            "        \"gravatar_id\": \"\",\n" +
            "        \"url\": \"https://api.github.com/users/tinyvampirepudge\",\n" +
            "        \"html_url\": \"https://github.com/tinyvampirepudge\",\n" +
            "        \"followers_url\": \"https://api.github.com/users/tinyvampirepudge/followers\",\n" +
            "        \"following_url\": \"https://api.github.com/users/tinyvampirepudge/following{/other_user}\",\n" +
            "        \"gists_url\": \"https://api.github.com/users/tinyvampirepudge/gists{/gist_id}\",\n" +
            "        \"starred_url\": \"https://api.github.com/users/tinyvampirepudge/starred{/owner}{/repo}\",\n" +
            "        \"subscriptions_url\": \"https://api.github.com/users/tinyvampirepudge/subscriptions\",\n" +
            "        \"organizations_url\": \"https://api.github.com/users/tinyvampirepudge/orgs\",\n" +
            "        \"repos_url\": \"https://api.github.com/users/tinyvampirepudge/repos\",\n" +
            "        \"events_url\": \"https://api.github.com/users/tinyvampirepudge/events{/privacy}\",\n" +
            "        \"received_events_url\": \"https://api.github.com/users/tinyvampirepudge/received_events\",\n" +
            "        \"type\": \"User\",\n" +
            "        \"site_admin\": false\n" +
            "    },\n" +
            "    \"html_url\": \"https://github.com/tinyvampirepudge/Android\",\n" +
            "    \"description\": \"GitHub上最火的Android开源项目,所有开源项目都有详细资料和配套视频\",\n" +
            "    \"fork\": true,\n" +
            "    \"url\": \"https://api.github.com/repos/tinyvampirepudge/Android\",\n" +
            "    \"forks_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/forks\",\n" +
            "    \"keys_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/keys{/key_id}\",\n" +
            "    \"collaborators_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/collaborators{/collaborator}\",\n" +
            "    \"teams_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/teams\",\n" +
            "    \"hooks_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/hooks\",\n" +
            "    \"issue_events_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/issues/events{/number}\",\n" +
            "    \"events_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/events\",\n" +
            "    \"assignees_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/assignees{/user}\",\n" +
            "    \"branches_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/branches{/branch}\",\n" +
            "    \"tags_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/tags\",\n" +
            "    \"blobs_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/git/blobs{/sha}\",\n" +
            "    \"git_tags_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/git/tags{/sha}\",\n" +
            "    \"git_refs_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/git/refs{/sha}\",\n" +
            "    \"trees_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/git/trees{/sha}\",\n" +
            "    \"statuses_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/statuses/{sha}\",\n" +
            "    \"languages_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/languages\",\n" +
            "    \"stargazers_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/stargazers\",\n" +
            "    \"contributors_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/contributors\",\n" +
            "    \"subscribers_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/subscribers\",\n" +
            "    \"subscription_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/subscription\",\n" +
            "    \"commits_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/commits{/sha}\",\n" +
            "    \"git_commits_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/git/commits{/sha}\",\n" +
            "    \"comments_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/comments{/number}\",\n" +
            "    \"issue_comment_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/issues/comments{/number}\",\n" +
            "    \"contents_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/contents/{+path}\",\n" +
            "    \"compare_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/compare/{base}...{head}\",\n" +
            "    \"merges_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/merges\",\n" +
            "    \"archive_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/{archive_format}{/ref}\",\n" +
            "    \"downloads_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/downloads\",\n" +
            "    \"issues_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/issues{/number}\",\n" +
            "    \"pulls_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/pulls{/number}\",\n" +
            "    \"milestones_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/milestones{/number}\",\n" +
            "    \"notifications_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/notifications{?since,all,participating}\",\n" +
            "    \"labels_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/labels{/name}\",\n" +
            "    \"releases_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/releases{/id}\",\n" +
            "    \"deployments_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/deployments\",\n" +
            "    \"created_at\": \"2017-02-21T02:40:15Z\",\n" +
            "    \"updated_at\": \"2017-02-21T02:40:15Z\",\n" +
            "    \"pushed_at\": \"2017-02-18T07:28:33Z\",\n" +
            "    \"git_url\": \"git://github.com/tinyvampirepudge/Android.git\",\n" +
            "    \"ssh_url\": \"git@github.com:tinyvampirepudge/Android.git\",\n" +
            "    \"clone_url\": \"https://github.com/tinyvampirepudge/Android.git\",\n" +
            "    \"svn_url\": \"https://github.com/tinyvampirepudge/Android\",\n" +
            "    \"homepage\": \"\",\n" +
            "    \"size\": 6,\n" +
            "    \"stargazers_count\": 0,\n" +
            "    \"watchers_count\": 0,\n" +
            "    \"language\": null,\n" +
            "    \"has_issues\": false,\n" +
            "    \"has_projects\": true,\n" +
            "    \"has_downloads\": true,\n" +
            "    \"has_wiki\": true,\n" +
            "    \"has_pages\": false,\n" +
            "    \"forks_count\": 0,\n" +
            "    \"mirror_url\": null,\n" +
            "    \"archived\": false,\n" +
            "    \"disabled\": false,\n" +
            "    \"open_issues_count\": 0,\n" +
            "    \"license\": null,\n" +
            "    \"allow_forking\": true,\n" +
            "    \"is_template\": false,\n" +
            "    \"topics\": [],\n" +
            "    \"visibility\": \"public\",\n" +
            "    \"forks\": 0,\n" +
            "    \"open_issues\": 0,\n" +
            "    \"watchers\": 0,\n" +
            "    \"default_branch\": \"master\"\n" +
            "}";

    /**
     * list
     */
    public static final String GITHUB_REPOS = "[\n" +
            "    {\n" +
            "        \"id\": 82627728,\n" +
            "        \"node_id\": \"MDEwOlJlcG9zaXRvcnk4MjYyNzcyOA==\",\n" +
            "        \"name\": \"Android\",\n" +
            "        \"full_name\": \"tinyvampirepudge/Android\",\n" +
            "        \"private\": false,\n" +
            "        \"owner\": {\n" +
            "            \"login\": \"tinyvampirepudge\",\n" +
            "            \"id\": 15034726,\n" +
            "            \"node_id\": \"MDQ6VXNlcjE1MDM0NzI2\",\n" +
            "            \"avatar_url\": \"https://avatars.githubusercontent.com/u/15034726?v=4\",\n" +
            "            \"gravatar_id\": \"\",\n" +
            "            \"url\": \"https://api.github.com/users/tinyvampirepudge\",\n" +
            "            \"html_url\": \"https://github.com/tinyvampirepudge\",\n" +
            "            \"followers_url\": \"https://api.github.com/users/tinyvampirepudge/followers\",\n" +
            "            \"following_url\": \"https://api.github.com/users/tinyvampirepudge/following{/other_user}\",\n" +
            "            \"gists_url\": \"https://api.github.com/users/tinyvampirepudge/gists{/gist_id}\",\n" +
            "            \"starred_url\": \"https://api.github.com/users/tinyvampirepudge/starred{/owner}{/repo}\",\n" +
            "            \"subscriptions_url\": \"https://api.github.com/users/tinyvampirepudge/subscriptions\",\n" +
            "            \"organizations_url\": \"https://api.github.com/users/tinyvampirepudge/orgs\",\n" +
            "            \"repos_url\": \"https://api.github.com/users/tinyvampirepudge/repos\",\n" +
            "            \"events_url\": \"https://api.github.com/users/tinyvampirepudge/events{/privacy}\",\n" +
            "            \"received_events_url\": \"https://api.github.com/users/tinyvampirepudge/received_events\",\n" +
            "            \"type\": \"User\",\n" +
            "            \"site_admin\": false\n" +
            "        },\n" +
            "        \"html_url\": \"https://github.com/tinyvampirepudge/Android\",\n" +
            "        \"description\": \"GitHub上最火的Android开源项目,所有开源项目都有详细资料和配套视频\",\n" +
            "        \"fork\": true,\n" +
            "        \"url\": \"https://api.github.com/repos/tinyvampirepudge/Android\",\n" +
            "        \"forks_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/forks\",\n" +
            "        \"keys_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/keys{/key_id}\",\n" +
            "        \"collaborators_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/collaborators{/collaborator}\",\n" +
            "        \"teams_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/teams\",\n" +
            "        \"hooks_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/hooks\",\n" +
            "        \"issue_events_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/issues/events{/number}\",\n" +
            "        \"events_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/events\",\n" +
            "        \"assignees_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/assignees{/user}\",\n" +
            "        \"branches_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/branches{/branch}\",\n" +
            "        \"tags_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/tags\",\n" +
            "        \"blobs_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/git/blobs{/sha}\",\n" +
            "        \"git_tags_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/git/tags{/sha}\",\n" +
            "        \"git_refs_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/git/refs{/sha}\",\n" +
            "        \"trees_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/git/trees{/sha}\",\n" +
            "        \"statuses_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/statuses/{sha}\",\n" +
            "        \"languages_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/languages\",\n" +
            "        \"stargazers_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/stargazers\",\n" +
            "        \"contributors_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/contributors\",\n" +
            "        \"subscribers_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/subscribers\",\n" +
            "        \"subscription_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/subscription\",\n" +
            "        \"commits_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/commits{/sha}\",\n" +
            "        \"git_commits_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/git/commits{/sha}\",\n" +
            "        \"comments_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/comments{/number}\",\n" +
            "        \"issue_comment_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/issues/comments{/number}\",\n" +
            "        \"contents_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/contents/{+path}\",\n" +
            "        \"compare_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/compare/{base}...{head}\",\n" +
            "        \"merges_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/merges\",\n" +
            "        \"archive_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/{archive_format}{/ref}\",\n" +
            "        \"downloads_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/downloads\",\n" +
            "        \"issues_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/issues{/number}\",\n" +
            "        \"pulls_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/pulls{/number}\",\n" +
            "        \"milestones_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/milestones{/number}\",\n" +
            "        \"notifications_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/notifications{?since,all,participating}\",\n" +
            "        \"labels_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/labels{/name}\",\n" +
            "        \"releases_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/releases{/id}\",\n" +
            "        \"deployments_url\": \"https://api.github.com/repos/tinyvampirepudge/Android/deployments\",\n" +
            "        \"created_at\": \"2017-02-21T02:40:15Z\",\n" +
            "        \"updated_at\": \"2017-02-21T02:40:15Z\",\n" +
            "        \"pushed_at\": \"2017-02-18T07:28:33Z\",\n" +
            "        \"git_url\": \"git://github.com/tinyvampirepudge/Android.git\",\n" +
            "        \"ssh_url\": \"git@github.com:tinyvampirepudge/Android.git\",\n" +
            "        \"clone_url\": \"https://github.com/tinyvampirepudge/Android.git\",\n" +
            "        \"svn_url\": \"https://github.com/tinyvampirepudge/Android\",\n" +
            "        \"homepage\": \"\",\n" +
            "        \"size\": 6,\n" +
            "        \"stargazers_count\": 0,\n" +
            "        \"watchers_count\": 0,\n" +
            "        \"language\": null,\n" +
            "        \"has_issues\": false,\n" +
            "        \"has_projects\": true,\n" +
            "        \"has_downloads\": true,\n" +
            "        \"has_wiki\": true,\n" +
            "        \"has_pages\": false,\n" +
            "        \"forks_count\": 0,\n" +
            "        \"mirror_url\": null,\n" +
            "        \"archived\": false,\n" +
            "        \"disabled\": false,\n" +
            "        \"open_issues_count\": 0,\n" +
            "        \"license\": null,\n" +
            "        \"allow_forking\": true,\n" +
            "        \"is_template\": false,\n" +
            "        \"topics\": [],\n" +
            "        \"visibility\": \"public\",\n" +
            "        \"forks\": 0,\n" +
            "        \"open_issues\": 0,\n" +
            "        \"watchers\": 0,\n" +
            "        \"default_branch\": \"master\"\n" +
            "    },\n" +
            "    {\n" +
            "        \"id\": 131961039,\n" +
            "        \"node_id\": \"MDEwOlJlcG9zaXRvcnkxMzE5NjEwMzk=\",\n" +
            "        \"name\": \"Android-AdvancedWebView\",\n" +
            "        \"full_name\": \"tinyvampirepudge/Android-AdvancedWebView\",\n" +
            "        \"private\": false,\n" +
            "        \"owner\": {\n" +
            "            \"login\": \"tinyvampirepudge\",\n" +
            "            \"id\": 15034726,\n" +
            "            \"node_id\": \"MDQ6VXNlcjE1MDM0NzI2\",\n" +
            "            \"avatar_url\": \"https://avatars.githubusercontent.com/u/15034726?v=4\",\n" +
            "            \"gravatar_id\": \"\",\n" +
            "            \"url\": \"https://api.github.com/users/tinyvampirepudge\",\n" +
            "            \"html_url\": \"https://github.com/tinyvampirepudge\",\n" +
            "            \"followers_url\": \"https://api.github.com/users/tinyvampirepudge/followers\",\n" +
            "            \"following_url\": \"https://api.github.com/users/tinyvampirepudge/following{/other_user}\",\n" +
            "            \"gists_url\": \"https://api.github.com/users/tinyvampirepudge/gists{/gist_id}\",\n" +
            "            \"starred_url\": \"https://api.github.com/users/tinyvampirepudge/starred{/owner}{/repo}\",\n" +
            "            \"subscriptions_url\": \"https://api.github.com/users/tinyvampirepudge/subscriptions\",\n" +
            "            \"organizations_url\": \"https://api.github.com/users/tinyvampirepudge/orgs\",\n" +
            "            \"repos_url\": \"https://api.github.com/users/tinyvampirepudge/repos\",\n" +
            "            \"events_url\": \"https://api.github.com/users/tinyvampirepudge/events{/privacy}\",\n" +
            "            \"received_events_url\": \"https://api.github.com/users/tinyvampirepudge/received_events\",\n" +
            "            \"type\": \"User\",\n" +
            "            \"site_admin\": false\n" +
            "        },\n" +
            "        \"html_url\": \"https://github.com/tinyvampirepudge/Android-AdvancedWebView\",\n" +
            "        \"description\": \"Enhanced WebView component for Android that works as intended out of the box\",\n" +
            "        \"fork\": true,\n" +
            "        \"url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView\",\n" +
            "        \"forks_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/forks\",\n" +
            "        \"keys_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/keys{/key_id}\",\n" +
            "        \"collaborators_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/collaborators{/collaborator}\",\n" +
            "        \"teams_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/teams\",\n" +
            "        \"hooks_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/hooks\",\n" +
            "        \"issue_events_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/issues/events{/number}\",\n" +
            "        \"events_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/events\",\n" +
            "        \"assignees_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/assignees{/user}\",\n" +
            "        \"branches_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/branches{/branch}\",\n" +
            "        \"tags_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/tags\",\n" +
            "        \"blobs_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/git/blobs{/sha}\",\n" +
            "        \"git_tags_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/git/tags{/sha}\",\n" +
            "        \"git_refs_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/git/refs{/sha}\",\n" +
            "        \"trees_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/git/trees{/sha}\",\n" +
            "        \"statuses_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/statuses/{sha}\",\n" +
            "        \"languages_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/languages\",\n" +
            "        \"stargazers_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/stargazers\",\n" +
            "        \"contributors_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/contributors\",\n" +
            "        \"subscribers_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/subscribers\",\n" +
            "        \"subscription_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/subscription\",\n" +
            "        \"commits_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/commits{/sha}\",\n" +
            "        \"git_commits_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/git/commits{/sha}\",\n" +
            "        \"comments_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/comments{/number}\",\n" +
            "        \"issue_comment_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/issues/comments{/number}\",\n" +
            "        \"contents_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/contents/{+path}\",\n" +
            "        \"compare_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/compare/{base}...{head}\",\n" +
            "        \"merges_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/merges\",\n" +
            "        \"archive_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/{archive_format}{/ref}\",\n" +
            "        \"downloads_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/downloads\",\n" +
            "        \"issues_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/issues{/number}\",\n" +
            "        \"pulls_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/pulls{/number}\",\n" +
            "        \"milestones_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/milestones{/number}\",\n" +
            "        \"notifications_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/notifications{?since,all,participating}\",\n" +
            "        \"labels_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/labels{/name}\",\n" +
            "        \"releases_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/releases{/id}\",\n" +
            "        \"deployments_url\": \"https://api.github.com/repos/tinyvampirepudge/Android-AdvancedWebView/deployments\",\n" +
            "        \"created_at\": \"2018-05-03T07:55:06Z\",\n" +
            "        \"updated_at\": \"2018-05-03T07:55:07Z\",\n" +
            "        \"pushed_at\": \"2018-04-18T00:21:04Z\",\n" +
            "        \"git_url\": \"git://github.com/tinyvampirepudge/Android-AdvancedWebView.git\",\n" +
            "        \"ssh_url\": \"git@github.com:tinyvampirepudge/Android-AdvancedWebView.git\",\n" +
            "        \"clone_url\": \"https://github.com/tinyvampirepudge/Android-AdvancedWebView.git\",\n" +
            "        \"svn_url\": \"https://github.com/tinyvampirepudge/Android-AdvancedWebView\",\n" +
            "        \"homepage\": \"\",\n" +
            "        \"size\": 431,\n" +
            "        \"stargazers_count\": 0,\n" +
            "        \"watchers_count\": 0,\n" +
            "        \"language\": \"Java\",\n" +
            "        \"has_issues\": false,\n" +
            "        \"has_projects\": true,\n" +
            "        \"has_downloads\": true,\n" +
            "        \"has_wiki\": false,\n" +
            "        \"has_pages\": false,\n" +
            "        \"forks_count\": 0,\n" +
            "        \"mirror_url\": null,\n" +
            "        \"archived\": false,\n" +
            "        \"disabled\": false,\n" +
            "        \"open_issues_count\": 0,\n" +
            "        \"license\": {\n" +
            "            \"key\": \"mit\",\n" +
            "            \"name\": \"MIT License\",\n" +
            "            \"spdx_id\": \"MIT\",\n" +
            "            \"url\": \"https://api.github.com/licenses/mit\",\n" +
            "            \"node_id\": \"MDc6TGljZW5zZTEz\"\n" +
            "        },\n" +
            "        \"allow_forking\": true,\n" +
            "        \"is_template\": false,\n" +
            "        \"topics\": [],\n" +
            "        \"visibility\": \"public\",\n" +
            "        \"forks\": 0,\n" +
            "        \"open_issues\": 0,\n" +
            "        \"watchers\": 0,\n" +
            "        \"default_branch\": \"master\"\n" +
            "    }\n" +
            "]";
}
